### ISSUE TITLE
Inkplate 5 batteryAndTemperatureRead.py fails

### ISSUE THREAD

**Issue by fovea1959** [e-radionicacom/Inkplate-micropython#29]
throws a Traceback when reading the temperature

```
Mono: clean 970ms (19ms ea), draw 381ms (63ms ea), total 1351ms
0
Mono: clean 971ms (19ms ea), draw 381ms (63ms ea), total 1352ms
Traceback (most recent call last):
  File "<stdin>", line 41, in <module>
  File "inkplate5.py", line 837, in readTemperature
  File "inkplate5.py", line 173, in read_temperature
OSError: [Errno 19] ENODEV
```

I'm using commit 103e107195186d86ce219b335b4c51a1d0b9105f

**Comment by rsoric** [comment]
Hi @fovea1959 

Sorry to hear you're experiencing this issue, I just tried to replicate it and you're right, the reason this is happening is because on the newer boards, VBAT_EN should be HIGH to enable the circuitry to measure the battery, I've fixed this in a quick patch, check out the commit here: https://github.com/SolderedElectronics/Inkplate-micropython/commit/1e896484466e7a21e8becceb149f94bffc0e354c

The temperature issue I bet has something to do with properly turning on the TPS65186, also via digital write, as it's not available over I2C when I try to scan it. I will have to look into the temperature issue more next week due to some time constraints, I hope the fixed readBattery functionality will be helpful to you.

-Rob

**Comment by rsoric** [comment]
Hi @fovea1959 

just figured out what it was, the TPS required to be powered on before reading data from it from I2C, and I've just added that functionality in the driver on the main branch as a bug fix, here is the commit: https://github.com/SolderedElectronics/Inkplate-micropython/commit/0c0406f9292774cd711175be93a0128f2a3d1b01

Closing this issue as this should now be totally resolved, the sketch works fine on Inkplate 5.
