### ISSUE TITLE
Font format?

### ISSUE THREAD

**Issue by mbanzi** [e-radionicacom/Inkplate-micropython#32]
I'm using Micropython on the Inkplate 6 and I realised the font format doesn't seem to follow any of the formats normally used to represent fonts in Micropython or Arduino code.

Is there any documentation on how to convert Fonts to your format??

**Comment by rsoric** [comment]
Hi @mbanzi 

We weren't playing around with custom fonts in Python but I've had a look at gfx_standard_font_01.py, It shows a comment with letter format and Key format. The first two bytes are the height and width of each character, followed by the bitmap, where "1" represents a drawn pixel. Let's have a look at the letter A. It's ?DDD?
Ascii to binary gives us:
? -> 0b00111111
D -> 0b01000100

And now, if we paste that in VScode and CTRL+F all the '1's for easy visualisation, we get this: 
![image](https://github.com/SolderedElectronics/Inkplate-micropython/assets/9110144/467fb94b-1f03-4e75-823a-b3a0ea8b47b4)

So that's how it works.

**Comment by rsoric** [comment]
Closing as there doesn't seem to be more activity on this.

@mbanzi if you have any more questions, don't hesitate to let us know via here or our [support](https://soldered.com/contact/).
