### ISSUE TITLE
Can't read battery level of Inkplate6COLOR

### ISSUE THREAD

**Issue by besi** [e-radionicacom/Inkplate-micropython#35]
I'm running the following code in order to read the battery level:

```python
from inkplate6COLOR import Inkplate
Inkplate.readBattery()
```

I will get the following error:

```
Inkplate.readBattery()
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/lib/inkplate6COLOR.py", line 473, in readBattery
AttributeError: type object 'Inkplate' has no attribute 'VBAT_EN'
```

**Comment by besi** [comment]
Apparently I have the version 2.2.0 from around Januar 2023

![Inkplate6_COLOR_3D v3](https://github.com/SolderedElectronics/Inkplate-micropython/assets/160412/3a06f4df-024c-4157-acd5-a9bdd5bd4622)

**Comment by rsoric** [comment]
Hi @besi 

really sorry for such a late reply, as we don't prioritize this repository. I've just made a push to dev where this issue is fixed on inkplate6COLOR, check out the example as well: https://github.com/SolderedElectronics/Inkplate-micropython/blob/dev/Examples/Inkplate6COLOR/batteryRead.py

Hopefully that works.
